run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    ignore-generated-header: true
    severity: error
    rules:
      # https://github.com/mgechev/revive#available-rules
      - name: exported
      - name: unused-parameter
      - name: unused-receiver
      - name: waitgroup-by-value

  funlen:
    lines: 270
    statements: 50

  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 35

  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    disable:
      - fieldalignment # too strict
      - shadow

  misspell:
    locale: US

issues:
  exclude-dirs:
    - .github
    - docs

  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - revive
        - scopelint
        - funlen
        - gocognit
        - gochecknoinits
        - errcheck
        - dupl
        - goconst
        - gosec
        - noctx
        - wrapcheck
        - tparallel
  exclude-use-default: false