services:
  app:
    image: article_api
    container_name: article_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile

  postgres:
    image: postgres:15.1
    container_name: article_postgres
    user: ${DB_USER}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 5s
      interval: 5s
      retries: 10