version: "3.7"
services:
  app:
    image: echo-clean
    container_name: article_management_api
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile

  postgres:
    image: postgres:15.1
    container_name: go_clean_arch_postgres
    volumes:
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: article
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U user
      timeout: 5s
      interval: 5s
      retries: 10
