// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "echo-clean/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

type AuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorRepository) EXPECT() *AuthorRepository_Expecter {
	return &AuthorRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AuthorRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthorRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AuthorRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *AuthorRepository_Expecter) Delete(ctx interface{}, id interface{}) *AuthorRepository_Delete_Call {
	return &AuthorRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *AuthorRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *AuthorRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *AuthorRepository_Delete_Call) Return(_a0 error) *AuthorRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthorRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *AuthorRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: ctx
func (_m *AuthorRepository) Fetch(ctx context.Context) ([]*entity.Author, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []*entity.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Author, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Author); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type AuthorRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthorRepository_Expecter) Fetch(ctx interface{}) *AuthorRepository_Fetch_Call {
	return &AuthorRepository_Fetch_Call{Call: _e.mock.On("Fetch", ctx)}
}

func (_c *AuthorRepository_Fetch_Call) Run(run func(ctx context.Context)) *AuthorRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthorRepository_Fetch_Call) Return(_a0 []*entity.Author, _a1 error) *AuthorRepository_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorRepository_Fetch_Call) RunAndReturn(run func(context.Context) ([]*entity.Author, error)) *AuthorRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AuthorRepository) GetByID(ctx context.Context, id int64) (*entity.Author, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Author, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Author); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AuthorRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *AuthorRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AuthorRepository_GetByID_Call {
	return &AuthorRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AuthorRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *AuthorRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *AuthorRepository_GetByID_Call) Return(_a0 *entity.Author, _a1 error) *AuthorRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.Author, error)) *AuthorRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, name
func (_m *AuthorRepository) Store(ctx context.Context, name string) (*entity.Author, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 *entity.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Author, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Author); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type AuthorRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *AuthorRepository_Expecter) Store(ctx interface{}, name interface{}) *AuthorRepository_Store_Call {
	return &AuthorRepository_Store_Call{Call: _e.mock.On("Store", ctx, name)}
}

func (_c *AuthorRepository_Store_Call) Run(run func(ctx context.Context, name string)) *AuthorRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthorRepository_Store_Call) Return(_a0 *entity.Author, _a1 error) *AuthorRepository_Store_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorRepository_Store_Call) RunAndReturn(run func(context.Context, string) (*entity.Author, error)) *AuthorRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, author
func (_m *AuthorRepository) Update(ctx context.Context, author *entity.Author) (*entity.Author, error) {
	ret := _m.Called(ctx, author)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Author) (*entity.Author, error)); ok {
		return rf(ctx, author)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Author) *entity.Author); ok {
		r0 = rf(ctx, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Author) error); ok {
		r1 = rf(ctx, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AuthorRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - author *entity.Author
func (_e *AuthorRepository_Expecter) Update(ctx interface{}, author interface{}) *AuthorRepository_Update_Call {
	return &AuthorRepository_Update_Call{Call: _e.mock.On("Update", ctx, author)}
}

func (_c *AuthorRepository_Update_Call) Run(run func(ctx context.Context, author *entity.Author)) *AuthorRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Author))
	})
	return _c
}

func (_c *AuthorRepository_Update_Call) Return(_a0 *entity.Author, _a1 error) *AuthorRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Author) (*entity.Author, error)) *AuthorRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorRepository creates a new instance of AuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorRepository {
	mock := &AuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
