name: Go Test

on:
  push:
    branches: ["main", "chore/upgrade-linter"]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          args: --config=./.golangci.yaml --timeout=10m

      - name: Test
        run: make tests
